{
  authentikRollout,
  legacyBasicAuthFallbackRoutes,
  lib,
  pkgs,
  routes,
}:
let
  # Backends are addressed by CLUSTER DNS NAME, never ClusterIP. A Service can be
  # deleted and recreated with a new ClusterIP without leaving a route pointing
  # into a black hole. Traefik multi-host rules are explicit.
  hostRule = hs: lib.concatMapStringsSep " || " (h: "Host(`${h}`)") hs;

  routeRule =
    r:
    let
      exclusions = lib.concatMapStrings (path: " && !Path(`${path}`) && !Path(`${path}/`)") (
        r.excludedPaths or [ ]
      );
    in
    if exclusions == "" then hostRule r.hosts else "(${hostRule r.hosts})${exclusions}";

  # Authentication is derived centrally so an individual administrator route
  # cannot silently omit either its active Authentik gate or rollback fallback.
  effectiveMiddlewares =
    name: r:
    let
      authentikProtected = builtins.elem name authentikRollout.protectedRoutes;
    in
    (r.middlewares or [ ])
    ++ lib.optional (
      !authentikProtected && builtins.elem name legacyBasicAuthFallbackRoutes
    ) "basic-auth@file"
    ++ lib.optional authentikProtected "authentik-forward-auth@file";

  # Always emit `middlewares` as JSON. Conditional indented-string interpolation
  # previously produced valid-looking YAML at the wrong depth and silently removed
  # authentication; an empty JSON sequence is accepted and structurally unambiguous.
  renderRoute =
    name: r:
    if r.enabled or true then
      pkgs.writeText "k8s-${name}.yml" ''
        # GENERATED by hosts/nixos/minas-tirith/traefik-routes.nix — DO NOT EDIT HERE.
        # Edits are overwritten on the next nixos-rebuild. Change the Nix file instead.
        #
        # Router is named k8s-${name}, deliberately NOT ${name}: while the docker copy of
        # a migrated service still exists (stopped, as the rollback), restarting it
        # recreates ${name}@docker with the same Host rule. Distinct names keep rollback
        # unambiguous — and once mattered more than that, because two routers on one host
        # used to TIE and traefik picked between them arbitrarily, which is how the traefik
        # dashboard ended up unauthenticated for an unknown period. The explicit priority
        # below now settles that tie deterministically in docker's favour; the distinct
        # name remains so the two are still tellable apart in logs and the dashboard.
        #
        # entryPoint is `https` — the real name. `websecure` does not exist on this
        # traefik; the names in traefik.yml are static config sitting in the dynamic
        # directory and are silently ignored.
        http:
          routers:
            k8s-${name}:
              rule: "${routeRule r}"
              entryPoints: [https]
              # priority 1 — the LOWEST. This is load-bearing, and it is what makes
              # installing a route BEFORE its Pod exists a safe thing to do.
              #
              # Traefik defaults a router's priority to the LENGTH OF ITS RULE, so a
              # docker router for the same host lands around 26 and this one, at 1,
              # can never outrank it. While the docker container is up it keeps the
              # hostname; the instant it stops, its router disappears and this one is
              # the only match left. The handover needs no timing.
              #
              # Without this the two routers tie, and traefik picks between equal
              # priorities arbitrarily. That is not theoretical: on 2026-08-07 a
              # minas rebuild installed the ten `media` wave routes while their
              # Deployments did not yet exist (manifests.nix is delivered from
              # PELARGIR, and only minas had been rebuilt). Traefik chose the dead
              # k8s router for three hostnames and requests/overseer/lidarr returned
              # 502 while their docker containers were healthy the whole time.
              #
              # Safe here because nothing else matches these hostnames — the only
              # other explicit priorities in traefik.yml (90/100) are on
              # dungeon.saldivar.io. Check that again before adding a catch-all
              # router, which would outrank every route in this file.
              priority: 1
              service: k8s-${name}
              middlewares: ${builtins.toJSON (effectiveMiddlewares name r)}
          services:
            k8s-${name}:
              loadBalancer:
                servers:
                  - url: "http://${r.serviceName or name}.${r.namespace}.svc.cluster.local:${toString r.port}"
      ''
    else
      pkgs.writeText "k8s-${name}.yml" ''
        # GENERATED disabled route. Keeping the file managed makes rollback remove a
        # previously-published router instead of leaving stale dynamic configuration.
        http: {}
      '';

  # mapAttrsToList preserves the evaluated attrset traversal/order used before the
  # split; filenames remain an explicit derivation of the catalog keys.
  rendered = lib.mapAttrsToList (name: r: {
    inherit name;
    file = renderRoute name r;
  }) routes;

  validProtectedRoutes = lib.filter (
    name: builtins.hasAttr name routes
  ) authentikRollout.protectedRoutes;

  authentikProtectedHosts = lib.unique (
    lib.concatMap (name: routes.${name}.hosts) validProtectedRoutes
    ++ lib.optional authentikRollout.protectDashboard "traefik.saldivar.io"
  );

  authentikGateEnabled = authentikProtectedHosts != [ ];
  authentikServerUrl = "http://authentik-server.authentik.svc.cluster.local:9000";

  # JSON is valid YAML and avoids optional-block indentation hazards. The callback
  # must bypass ForwardAuth and reach the embedded outpost for protected hosts.
  authentikGateConfig =
    if authentikGateEnabled then
      {
        http = {
          middlewares.authentik-forward-auth.forwardAuth = {
            address = "${authentikServerUrl}/outpost.goauthentik.io/auth/traefik";
            trustForwardHeader = true;
            authResponseHeaders = [
              "X-authentik-username"
              "X-authentik-groups"
              "X-authentik-entitlements"
              "X-authentik-email"
              "X-authentik-name"
              "X-authentik-uid"
              "X-authentik-jwt"
              "X-authentik-meta-jwks"
              "X-authentik-meta-outpost"
              "X-authentik-meta-provider"
              "X-authentik-meta-app"
              "X-authentik-meta-version"
            ];
          };
          routers = {
            authentik-callback = {
              rule = "(${hostRule authentikProtectedHosts}) && PathPrefix(`/outpost.goauthentik.io/`)";
              entryPoints = [ "https" ];
              priority = 10000;
              service = "authentik-outpost";
            };
          }
          // lib.optionalAttrs authentikRollout.protectDashboard {
            authentik-traefik-dashboard = {
              rule = "Host(`traefik.saldivar.io`)";
              entryPoints = [ "https" ];
              priority = 9000;
              service = "api@internal";
              # The lower-priority hand-maintained dashboard router retains BasicAuth
              # for rollback; this active override is Authentik-only for one SSO flow.
              middlewares = [ "authentik-forward-auth@file" ];
            };
          };
          services.authentik-outpost.loadBalancer.servers = [
            { url = authentikServerUrl; }
          ];
        };
      }
    else
      {
        http = { };
      };

  authentikGateFile = pkgs.writeText "k8s-authentik-gate.yml" ''
    # GENERATED by hosts/nixos/minas-tirith/traefik-routes.nix — DO NOT EDIT.
    ${builtins.toJSON authentikGateConfig}
  '';

  managedNames = (map (e: "k8s-${e.name}.yml") rendered) ++ [ "k8s-authentik-gate.yml" ];
in
{
  inherit
    authentikGateEnabled
    authentikGateFile
    managedNames
    rendered
    ;
}
