# vLLM on nardol's 4090.
#
# ⛔ EXCLUSIVE WITH GAMING, and that is a VRAM fact, not a policy choice. 24 GB
# cannot hold a served model and a game at once, and consumer cards have no MIG
# to partition it with. The arbitration lives in ./gaming-arbitration.nix.
#
# Every choice a model swap touches is an option below, because the model WILL
# change: quantized checkpoints get re-cut, Qwen ships a new generation, or a
# benchmark on real work says something else is better. Swapping should be
# editing `model` and `quantization`, not rewriting a service.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.nardol.inference;

  # Shared with pkgs/amon-din.nix so the Mac menu cannot offer a model this host
  # does not serve. See the header of that file for why it is data, not options.
  profileData = import ../../../lib/inference-profiles.nix;

  ggufRoot = "${cfg.stateDir}/gguf";
  profileStateDir = "/var/lib/nardol-inference";

  # A profile field, or the module-level option when the profile says null. The
  # GPU-only 27B therefore keeps every default documented above instead of
  # restating it in lib/inference-profiles.nix.
  or' = a: b: if a == null then b else a;

  # ⛔ THE CONTAINER SEES /models, NOT /srv. Flash-style cuts live in
  # subdirectories, so this maps the host path rather than taking `baseNameOf`,
  # which silently flattened `flash-next/foo.gguf` to `foo.gguf` and produced a
  # file-not-found the server reports only in its own log.
  containerModelPath =
    f:
    if lib.hasPrefix "${ggufRoot}/" f then
      "/models/" + lib.removePrefix "${ggufRoot}/" f
    else
      throw "nardol.inference: GGUF ${f} is not under ${ggufRoot}, so the container cannot see it";

  ikProfileArgs =
    p:
    [
      "-m"
      (containerModelPath (or' p.ggufFile cfg.ggufFile))
      "--host"
      "0.0.0.0"
      "--port"
      "8080"
      "-ngl"
      "99"
      "--jinja"
      "-fa"
      "on"
      # ⛔ ik #1932 reports recurrent-state cross-conversation corruption
      # with three or more slots on hybrid models. Single user; there is
      # nothing to gain from a multi-user default and a correctness bug
      # to lose.
      "--parallel"
      "1"
      "-ctk"
      (or' p.kvType cfg.llamaKvType)
      "-ctv"
      (or' p.kvType cfg.llamaKvType)
    ]
    ++ lib.optionals (or' p.maxModelLen cfg.maxModelLen != null) [
      "-c"
      (toString (or' p.maxModelLen cfg.maxModelLen))
    ]
    ++ lib.concatMap (stage: [
      "--spec-type"
      stage
    ]) (or' p.specStages cfg.specStages)
    ++ lib.optionals (or' p.mtpRequantizeOutputTensor cfg.mtpRequantizeOutputTensor != null) [
      "-mtprot"
      (or' p.mtpRequantizeOutputTensor cfg.mtpRequantizeOutputTensor)
    ]
    # Hybrid CPU/GPU offload. Only a profile sets these: on a model that fits
    # the card they are meaningless, and --n-cpu-moe 0 is not the same as
    # omitting it.
    ++ lib.optionals (p.cpuMoe != null) [
      "--n-cpu-moe"
      (toString p.cpuMoe)
    ]
    ++ lib.optionals (p.batchSize != null) [
      "-b"
      (toString p.batchSize)
    ]
    ++ lib.optionals (p.ubatchSize != null) [
      "-ub"
      (toString p.ubatchSize)
    ]
    ++ lib.optionals (cfg.ctxCheckpoints != null) [
      "--ctx-checkpoints"
      (toString cfg.ctxCheckpoints)
    ]
    ++ lib.optionals (cfg.chatTemplateKwargs != null) [
      "--chat-template-kwargs"
      cfg.chatTemplateKwargs
    ]
    ++ p.extraArgs
    ++ cfg.extraArgs;

  # ⛔ PLAIN `#!/bin/sh`, AND NOTHING FROM THIS FLAKE'S bash. This script runs
  # INSIDE the container, which has no /nix/store mounted — `pkgs.writeShellScript`
  # would bake a shebang that does not exist there and the unit would fail at
  # exec with a bare "no such file or directory" naming a path that plainly
  # exists on the host. Only `read`, `case` and `exec` are used, all builtins.
  ikStartScript = pkgs.writeTextFile {
    name = "ikllama-start";
    executable = true;
    text = ''
      #!/bin/sh
      # Generated by hosts/nixos/nardol/inference.nix — do not edit in place.
      set -eu

      PROFILE="${profileData.default}"
      if [ -r ${profileStateDir}/profile ]; then
        read -r PROFILE < ${profileStateDir}/profile || PROFILE="${profileData.default}"
      fi

      case "$PROFILE" in
      ${lib.concatStringsSep "\n" (
        lib.mapAttrsToList (name: p: ''
          ${name})
            echo "ikllama: serving profile ${name}" >&2
            exec ${cfg.ikLlamaServer} ${lib.escapeShellArgs (ikProfileArgs p)}
            ;;'') profileData.profiles
      )}
        *)
          # ⛔ FALL BACK, DO NOT FAIL. A profile can vanish from the flake while
          # a name sits in the state file — a rollback, a rename, a deploy of an
          # older generation. Refusing to start would take the endpoint down for
          # a stale string, and Home Assistant would lose its backend over a
          # typo. Serving the default and saying so in the log is recoverable.
          echo "ikllama: unknown profile '$PROFILE'; serving ${profileData.default}" >&2
          exec ${cfg.ikLlamaServer} ${
            lib.escapeShellArgs (ikProfileArgs profileData.profiles.${profileData.default})
          }
          ;;
      esac
    '';
  };

  # The switcher, on nardol rather than in the menu, so the same operation is
  # available over SSH, from a script, and from the Mac without three copies of
  # the validation.
  nardolModel = pkgs.writeShellApplication {
    name = "nardol-model";
    runtimeInputs = with pkgs; [
      systemd
      curl
      coreutils
    ];
    text = ''
      set -euo pipefail
      STATE=${profileStateDir}/profile
      DEFAULT=${profileData.default}
      PROFILES="${lib.concatStringsSep " " (lib.attrNames profileData.profiles)}"

      current() { [ -r "$STATE" ] && cat "$STATE" || echo "$DEFAULT"; }

      case "''${1:-list}" in
        list)
          for p in $PROFILES; do
            if [ "$p" = "$(current)" ]; then echo "* $p"; else echo "  $p"; fi
          done
          ;;
        current) current ;;
        switch)
          want="''${2:-}"
          # ⛔ VALIDATE BEFORE WRITING. An unvalidated name is accepted here,
          # falls back inside the container, and leaves the menu showing a model
          # the server is not running — a silent lie is worse than a refusal.
          for p in $PROFILES; do [ "$p" = "$want" ] && ok=1; done
          if [ "''${ok:-0}" != 1 ]; then
            echo "unknown profile '$want'; known: $PROFILES" >&2
            exit 1
          fi
          if [ "$want" = "$(current)" ] && systemctl is-active --quiet docker-ikllama; then
            echo "already serving $want"; exit 0
          fi
          mkdir -p ${profileStateDir}
          echo "$want" > "$STATE"

          # ⛔ NEVER TOUCH THE UNIT WHILE A GAME IS LIVE. nardol-gaming.target
          # Conflicts= docker-ikllama, and systemd resolves a conflict by
          # stopping the OTHER side — so `systemctl restart docker-ikllama`
          # during a session does not queue behind the game, it TEARS THE
          # SESSION DOWN mid-stream. gaming-arbitration.nix learned this the
          # expensive way; a menu item must not re-learn it.
          #
          # Recording the choice is still correct: nardol-inference-restore
          # starts the unit when gaming ends, and the entrypoint reads this file
          # at exec, so the new model arrives with the restore.
          if systemctl is-active --quiet nardol-gaming.target; then
            echo "recorded $want; a session is live, so it starts with the next restore"
            exit 0
          fi

          if ! systemctl is-active --quiet docker-ikllama; then
            echo "recorded $want; inference is not running, so it starts with the next start"
            exit 0
          fi

          # ⚠️ RESTART, NOT start: the model is chosen when the container execs,
          # so a running server keeps serving the old one until it is replaced.
          systemctl restart docker-ikllama
          # Loading 15-90 GiB is not instant and a menu that returns before the
          # endpoint answers invites a second click on a half-started server.
          for _ in $(seq 1 240); do
            if curl -fsS -m 2 http://127.0.0.1:${toString cfg.port}/health >/dev/null 2>&1; then
              echo "serving $want"; exit 0
            fi
            sleep 2
          done
          echo "switched to $want but /health did not answer within 480s" >&2
          exit 1
          ;;
        *) echo "usage: nardol-model [list|current|switch <profile>]" >&2; exit 2 ;;
      esac
    '';
  };
in
{
  options.nardol.inference = {
    enable = lib.mkEnableOption "an inference server on nardol's GPU";

    engine = lib.mkOption {
      type = lib.types.enum [
        "vllm"
        "llama-cpp"
        "ik-llama"
      ];
      default = "vllm";
      description = ''
        Which runtime serves the model. ONE AT A TIME — 24 GB cannot hold two
        copies of a 27B, so these are alternatives rather than peers, and A/B
        means switching this option and re-running scripts/inference-ab.py.

        ik-llama is ikawrakow's fork, carrying its own IQK quantization formats
        and a published 32k config claiming 16 GB against upstream's 22 — on a
        24 GB card that difference is context. It is built from source into a
        local image because there is no published container and it is not in
        nixpkgs; see pkgs note in the runtime image's Dockerfile for why it must
        be compiled under `docker run --gpus=all` rather than `docker build`.

        vllm is the incumbent and the control. llama-cpp is the challenger, for
        a specific reason: every vLLM-format INT4 cut of this model is ~20-21 GB
        because ~5.0B of 27.8B parameters stay BF16 (embeddings, lm_head, and
        the 48 GatedDeltaNet layers). GGUF quantizes those too, so Q4_K_M is
        16.8 GB — about 4 GB more headroom, which is the difference between
        running eager at 32k and running graphs at far more.

        Published 4090 figures put llama.cpp at 37-47 tok/s decode against our
        measured 22, but those come from a harness that folds prefill into
        decode and never exercises the tools API. Trust scripts/inference-ab.py
        over them.
      '';
    };

    ggufFile = lib.mkOption {
      type = lib.types.str;
      default =
        if cfg.engine == "ik-llama" then
          "/srv/inference/gguf/Qwen3.8-27B-MTP-IQ4_KS.gguf"
        else
          "/srv/inference/gguf/Qwen3.6-27B-Q4_K_M.gguf";
      defaultText = lib.literalExpression ''
        if engine == "ik-llama"
        then "/srv/inference/gguf/Qwen3.8-27B-MTP-IQ4_KS.gguf"
        else "/srv/inference/gguf/Qwen3.6-27B-Q4_K_M.gguf"'';
      description = ''
        Path to the GGUF, used by the llama-cpp and ik-llama engines.

        ⛔ THE DEFAULT FOLLOWS THE ENGINE, AND SWAPPING ONE WITHOUT THE OTHER
        SILENTLY COSTS HALF THE THROUGHPUT. `specStages` drafts with the
        model's own MTP head, and those tensors exist only in an MTP cut — point
        ik-llama at a plain IQ4_KS or Q4_K_M file and the mtp stage cannot load.
        Measured 2026-09-13 on this card: MTP is the single largest win
        available here, 50.8 -> 106.1 tok/s on code, so losing it is not subtle.

        ⚠️ Many community GGUFs labelled "MTP" strip the MTP tensors during
        re-quantization while keeping the metadata flag, which fails at load
        rather than degrading. Verify the stage actually initialised in the
        server banner before trusting a benchmark from a new file.

        IQ4_KS is ikawrakow's own recommendation for this model family, at
        ~0.14% quantization error — and it is an ik-only format, which is part
        of why this engine exists. The llama-cpp path stays on Q4_K_M because
        mainline cannot read IQ4_KS.

        THE MODEL MOVED 3.6 -> 3.8 ON 2026-09-17, and the generation is worth
        more than any flag on this list. Same architecture, same 27B, same
        15.75 GiB on the card, so nothing else here had to change:

          benchmark (Qwen's own, Claude Code harness)   3.6     3.8
          SWE-bench Pro                                 53.5    61.7
          Terminal-Bench 2.1                            63.4    73.0
          DeepSWE 1.1                                   13.3    42.2
          LiveCodeBench v6                              83.9    90.3

        DeepSWE 13.3 -> 42.2 is the one that matters for this host: it is an
        agentic-coding benchmark, and that is what the endpoint is for.

        ⚠️ VENDOR NUMBERS, at BF16, on Qwen's harness — not measured here and
        not independent. What IS independently measured is that the quantization
        costs nothing: Quesma ran Terminal-Bench 2.1 (2026-08-26) and found
        Q4_K_M matching BF16, with their BF16 run reproducing Qwen's own figure.
        ubergarm's perplexity for the file below is 6.9938 against 6.9540 at
        BF16, i.e. +0.57%.

        ⛔ RE-MEASURE THROUGHPUT AFTER THIS SWAP RATHER THAN ASSUMING IT HELD.
        The numbers throughout this file were taken on 3.6 and every one of them
        is now a claim about a model that is no longer served. The MTP head was
        retrained, so draft acceptance — and therefore `specStages`, `n_max` and
        the whole speculation story — is the thing most likely to have moved.
      '';
    };

    llamaCppImage = lib.mkOption {
      type = lib.types.str;
      default = "ghcr.io/ggml-org/llama.cpp@sha256:6ac921528d613deb0fd142c654735e594a446a1c37a069eeab08d8fd974d4bec";
      description = ''
        Digest-pinned server-cuda image.

        ⚠️ The fused CUDA GATED_DELTA_NET kernel only landed in PR #19504,
        available from build b8233. An older binary runs this architecture but
        not at current speed, so a benchmark against one is not evidence about
        llama.cpp — verify the build in the server banner before trusting any
        number from it.
      '';
    };

    model = lib.mkOption {
      type = lib.types.str;
      default = "palmfuture/Qwen3.6-27B-GPTQ-Int4";
      description = ''
        Hugging Face model id, or a path under stateDir.

        A GPTQ-Int4 cut of Qwen3.6-27B, chosen for its CALIBRATION rather than
        its format: 256 domain-mixed sequences (102 allenai/c4, 77 tulu-3-sft,
        51 codeparrot, 26 MATH-500), group_size=32, 100% GPTQ success with 0%
        RTN fallback, and MTP speculative-decoding weights verified on vLLM
        0.21.0. Contrast the data-free AWQ builds in circulation, which carry
        the same "AWQ" label and none of the quality.

        ⚠️ IT IS 20 GB ON DISK, NOT THE ~15 GB A 27B INT4 IMPLIES. group_size=32
        carries far more scale/zero overhead than the usual 128, and the MTP
        weights add more. On a 23.52 GiB card that leaves ~3.5 GB for KV cache,
        Mamba state, activations and CUDA graphs — which is why this host runs
        eager at 32k context instead of with graphs at 200k+.

        A leaner cut (group_size=128, no bundled MTP) should free several GB and
        is the FIRST thing to try if context length or decode speed disappoints.
        That is the whole reason these are options.

        ⚠️ Community checkpoint, and it publishes no benchmarks of the quantized
        model against full precision. If output quality ever looks off, re-cut
        or re-source this before blaming the flags.

        Base model chosen 2026-09-12 on evidence, not vibes: Qwen3.6-27B scores
        77.2% on SWE-bench Verified, beating Qwen3.5-397B-A17B (76.2%) with
        14.7x fewer total parameters, and vLLM's own recipe lists Int4 on a
        single 24 GB GPU as a supported tier. The obvious alternative,
        Qwen3-Coder-30B-A3B, is explicitly code- and agent-targeted but scores
        only ~50-52% on the same benchmark — a gap far larger than its speed
        advantage is worth for a single user.
      '';
    };

    quantization = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = ''
        ⛔ null MEANS AUTO-DETECT, AND THAT IS FASTER THAN NAMING IT.

        vLLM reads the quantization method from the checkpoint's own config and
        will promote a GPTQ checkpoint to the gptq_marlin kernel when the
        hardware supports it. Passing --quantization gptq explicitly can pin it
        to the reference GPTQ kernel instead and quietly cost throughput, so
        leave this null unless a checkpoint genuinely cannot be detected.

        ⚠️ CALIBRATION, NOT FORMAT, DECIDES QUALITY HERE.

        "Give Me BF16 or Give Me Death" measures W4A16-INT4 at 80.5 pass@1 on
        HumanEval against W8A8-FP8 at 80.0 — 4-bit weight-only is not the
        handicap for code that folklore says it is. What DOES hurt is bad
        calibration: the same paper attributes GPTQ beating AWQ to better
        calibration data rather than the algorithm, and notes random-token
        calibration degrades accuracy at low bitwidth.

        So prefer a checkpoint whose calibration set is documented and
        code-heavy. At least one published Qwen3.6-27B AWQ build uses DATA-FREE
        quantization; the label says AWQ and the quality will not.

        FP8 is not an option on this card regardless: 27 GB of weights against
        24 GB of VRAM. vLLM's recipe puts FP8 on a 40 GB GPU.
      '';
    };

    maxModelLen = lib.mkOption {
      type = lib.types.nullOr lib.types.int;
      default =
        if cfg.engine == "vllm" then
          32768
        else if cfg.engine == "ik-llama" then
          202752
        else
          65536;
      defaultText = lib.literalExpression ''
        if engine == "vllm" then 32768
        else if engine == "ik-llama" then 202752
        else 65536'';
      description = ''
        ⛔ null DOES NOT MEAN "let vLLM pick something sensible". It means the
        model's NATIVE length, which here is 262144, and on 24 GB that does not
        fit: engine init died with
          torch.OutOfMemoryError: Tried to allocate 1.53 GiB.
          GPU has 23.52 GiB total, of which 816.75 MiB is free.
        and systemd restarted it 189 times. Measured 2026-09-13.

        ⛔ THE CEILING IS ENGINE-DEPENDENT, so the default follows the engine.
        Setting one number for both is a trap: 65536 runs fine under llama.cpp
        in 18.5 GB, and under vLLM it dies with
          ValueError: max seq len (65536) needs 2.3 GiB KV cache, larger than
          the available KV cache memory (1.56 GiB)
        because vLLM's weights are 20 GB against llama.cpp's 16.8. The condition
        is written as "vllm or not" rather than naming one GGUF engine, so a
        fourth engine inherits the GGUF ceiling instead of vLLM's. Measured
        2026-09-13 by flipping `engine` back with the value still pinned.

        32768 is what the vLLM checkpoint actually starts at, found by bisection
        on the live card 2026-09-13. It is far below the 214k the KV arithmetic
        promises, for a reason the arithmetic could not know: this checkpoint is
        20 GB on disk, not the ~15 GB a 27B Int4 suggests, because group_size=32
        carries heavy scale/zero overhead and the MTP speculative-decoding
        weights are bundled in. 20 GB of weights on a 23.52 GiB card leaves ~3.5
        GB for everything else.

        ⛔ 202752 FOR ik-llama IS A MEASURED CEILING, NOT A GUESS, AND THE
        NUMBER ABOVE IT IS A CRASH. Established 2026-09-13 by filling the
        context, not by starting the server — a config that STARTS at a given
        -c will still die partway in. Each ceiling below was driven to ~98.6%
        occupancy from a cold container, twice, with VRAM sampled continuously
        rather than read once after the fact:

          ceiling   peak VRAM   spare   near-full runs   steps below failure
          180224      23,188    1,376        ok                  16
          190464      23,492    1,072       2/2                  11
          202752      23,832      732       2/2                   5
          210944      24,018      546       2/2                   1
          212992         ---      ---   CUDA OOM, exit 139        0

        212992 is the measured wall: it starts, then dies after reaching the
        210,944 checkpoint. The client sees RemoteDisconnected and the container
        SIGSEGVs; systemd restarts it, losing the request. That failure arrives
        precisely when the context is genuinely full — i.e. during the long
        agentic turn the context was raised for — so it will never show up in
        light use.

        202752 rather than the maximum 210944 because of the LAST column, not
        the memory one. 210944 is reproducibly fine today and sits ONE 2048-step
        from the wall; a driver update, an ik rebuild, or an allocator change
        moves that wall and turns a working deployment into a crashing one.
        202752 keeps five steps of slack and 40% more headroom for 8,192 fewer
        tokens.

        ⚠️ Margin is NOT what makes this safe against gaming. A game takes
        gigabytes; no amount of spare megabytes survives that. Exclusivity is
        gaming-arbitration's job, and that has not been tested end to end.

        ⛔ Raise this only against a successful start, never on arithmetic. Arithmetic says ~214k tokens is affordable — the hybrid
        architecture carries a KV cache on only 16 of its 64 layers, so
        16 x 2 x 4 heads x 256 dim x 1 byte = 32 KiB/token at FP8 — but that is
        a ceiling that ignores DeltaNet recurrent state, allocator overhead,
        activations and CUDA graphs. Set a number only to constrain it BELOW
        what vLLM measures, never to assert something above it.
      '';
    };

    kvCacheDtype = lib.mkOption {
      type = lib.types.str;
      default = "fp8";
      description = ''
        Halves KV cache against bf16, which is what buys the long context.

        ⛔ NEVER ADD --calculate-kv-scales. vLLM issue #37554 reports it
        producing a CORRUPTED fp8 KV cache on hybrid GatedDeltaNet+Attention
        models, which is exactly this architecture. Corruption, not a crash:
        the server runs and the answers quietly get worse. Use a checkpoint
        carrying calibrated scales instead.
      '';
    };

    enablePrefixCaching = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        The single highest-value flag for coding work, and it is not close.
        Measured on this architecture: a 25k-token document takes 22.4s to first
        token cold and 0.56s on a cached prefix — a 40x difference. Coding means
        resending the same files, so nearly every request is a cache hit.

        ⚠️ vLLM's recipe calls prefix caching experimental in "align" mode for
        Mamba-style components, and this model's 48 DeltaNet layers are exactly
        that. Verify it on the deployed version rather than trusting it: the
        flag doing the most work is the one worth proving.
      '';
    };

    gpuMemoryUtilization = lib.mkOption {
      type = lib.types.float;
      default = 0.95;
      description = ''
        Fraction of VRAM vLLM may claim for weights plus KV cache.

        ABOVE the 0.9 default, which is unusual and deliberate. The weights
        alone are ~20 GB of a 23.52 GiB card, so at 0.88 the budget (20.7 GB)
        barely exceeded the weights and the KV cache got a few hundred MB —
        engine init died on CUDA OOM. Running eager (below) frees the headroom
        that a high utilisation would otherwise steal from CUDA graphs.
      '';
    };

    enforceEager = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        ⛔ REQUIRED WITH THIS CHECKPOINT. CUDA graphs do not fit.

        Measured by bisection 2026-09-13: capture-size 256 and 64 both failed
        (OOM, then a start that never completed), while eager mode started
        cleanly with a 43,690-token KV cache. CUDA graphs allocate outside the
        gpu-memory-utilization budget, and there is nothing left to allocate
        from once 20 GB of weights are resident.

        The cost is decode throughput — graphs mainly help small-batch decode,
        which is exactly the single-user case. That is a real loss, and the
        right fix is a LEANER CHECKPOINT rather than more tuning here. See the
        note on `model`.
      '';
    };

    maxCudagraphCaptureSize = lib.mkOption {
      type = lib.types.nullOr lib.types.int;
      default = null;
      description = ''
        Ignored while enforceEager is true. Kept as an option because a leaner
        checkpoint would make CUDA graphs affordable again, at which point this
        is the knob vLLM's recipe says to reach for.
      '';
    };

    llamaKvType = lib.mkOption {
      type = lib.types.str;
      default = if cfg.engine == "ik-llama" then "q4_0" else "q8_0";
      defaultText = lib.literalExpression ''if engine == "ik-llama" then "q4_0" else "q8_0"'';
      description = ''
        ⛔ q4_0 IS WHAT BUYS THE CONTEXT, AND IT MEASURABLY COSTS NOTHING.
        At q8_0 the KV cache is ~38 KiB/token and 202752 does not fit at all.

        The obvious worry is that halving KV precision quietly degrades output.
        Tested 2026-09-13 head to head at ~43k tokens — a length BOTH hold, so
        KV precision is the only variable — with identical prompts and greedy
        decoding, three trials each:

          task                          q8_0   q4_0
          multi-needle w/ 4 distractors  3/3    3/3
          verbatim quotation             3/3    3/3
          cross-document synthesis       3/3    3/3
          long-code bug find             3/3    3/3
          long-form degeneration         3/3    3/3
          tool call under load           3/3    3/3

        Recall was also perfect at 15/50/85% depth out to 174k tokens, and a
        request at 99.0% occupancy returned the right answer.

        ⚠️ 18/18 against 18/18 is a CEILING EFFECT. It shows q4_0 is not worse
        at this difficulty; it cannot prove the two are identical. A harder
        battery might separate them.

        ⛔ DO NOT "SAVE MORE" WITH iq4_nl. It has the same footprint as q4_0, so
        it buys nothing, and on a 200k coding prompt it degenerated into
        repeating `1.` for the whole budget while reporting 43.3 tok/s against
        q4_0's 28.5. A faster number for useless output. Judge a KV type by
        reading what it produced, never by its throughput.

        llama.cpp spells KV quantisation differently from vLLM: q8_0 / q4_0
        rather than fp8. q8_0 remains right for the llama-cpp path, which runs
        at 65536 where the cache is not the binding constraint.
      '';
    };

    toolCallParser = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = "qwen3_xml";
      description = ''
        ⛔ WITHOUT THIS, TOOL CALLING IS NOT MERELY DEGRADED — IT IS REFUSED.

        vLLM rejects `tool_choice: auto` outright with HTTP 400:
          "auto" tool choice requires --enable-auto-tool-choice and
          --tool-call-parser to be set
        so Home Assistant would fail on every request. Found 2026-09-13 by
        scripts/inference-ab.py on the first run against our own deployment;
        nothing in the published 4090 benchmark would have caught it, because
        that harness never submits a tools array.

        qwen3_xml matches what this model's chat template actually emits —
        verified by reading the template out of the checkpoint rather than
        guessing: <tool_call><function=name><parameter=x>value</parameter>.
        This build also registers qwen3_coder, the older name for the same
        family; try it if the parser ever stops matching.

        ⚠️ llama.cpp issue #26763 reports THIS format silently absorbing
        subsequent protocol text into an argument when whitespace before
        </parameter> is missing, closed as not planned. Whichever runtime wins,
        validate tool arguments rather than trusting a 200 response.
      '';
    };

    port = lib.mkOption {
      type = lib.types.port;
      default = 8000;
      description = "OpenAI-compatible endpoint. Home Assistant 2026.8's built-in client speaks this.";
    };

    image = lib.mkOption {
      type = lib.types.str;
      default = "vllm/vllm-openai@sha256:a230095847e93bd4df9888b33dab956fa9504537b828a23657d2b26fed57b5c9";
      description = ''
        Digest-pinned, matching how ./wolf/image-config-policy.nix pins Wolf. A
        tag would let an upstream rebuild change inference behaviour with no
        commit here, which is precisely the drift this fleet's checks exist to
        prevent. This digest is v0.21.0 — deliberately NOT the newest (v0.29.0
        exists). 0.21.0 is the version the default checkpoint's MTP speculative
        decoding weights were actually verified against, and a verified pairing
        beats a newer one for something whose failure mode is subtly worse
        output rather than a crash.
      '';
    };

    ikLlamaImage = lib.mkOption {
      type = lib.types.str;
      default = "ik-llama:local";
      description = ''
        Locally built, so this is a tag rather than a digest — the one image
        here that is not content-addressed. The git revision is baked in at
        /BUILD_REV and reported by `--version`, which is what makes a benchmark
        number traceable; record it alongside any result.
      '';
    };

    ikLlamaServer = lib.mkOption {
      type = lib.types.str;
      default = "/opt/ik/build/bin/llama-server";
      description = ''
        The server binary INSIDE the ik image.

        ⛔ NAMED BECAUSE THE ENTRYPOINT IS OVERRIDDEN. Model switching works by
        replacing the image's entrypoint with a generated script that picks a
        profile and execs this path, so the path the image would have used by
        itself is no longer consulted. Read it back out of the image after any
        rebuild that moves the build directory:
          docker image inspect ik-llama:local --format '{{.Config.Entrypoint}}'
        Verified 2026-09-17 against the deployed image (rev 3bb386e).

        ⚠️ A wrong value here fails at exec inside the container, so the unit
        flaps with no server log at all — check `docker logs ikllama` rather
        than the endpoint when a switch produces silence.
      '';
    };

    specStages = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ "mtp:n_max=8" ];
      example = [ "mtp" ];
      description = ''
        Speculative decoding stages for ik-llama, one `--spec-type` each.

        ⛔ THIS IS THE BIGGEST SINGLE LEVER ON THIS HOST. Measured 2026-09-13,
        median tok/s over 12 unique code and 6 unique prose prompts, container
        recreated between configs:

          no speculation                      code  50.8   prose 50.8
          ngram-mod alone                     code  52.1   prose 51.7
          ngram-mod + mtp                     code  88.6   prose 77.1
          mtp                                 code 105.4   prose 90.1

        MTP is lossless by construction — the draft is verified against the same
        model, so greedy output is token-identical with and without it. None of
        this trades quality for speed. A cross-vocabulary DRAFT MODEL is a
        different mechanism and is NOT safe: it translates tokens between
        vocabularies and silently breaks JSON braces and tool-call boundaries,
        which is a corruption you would find in production, not in a benchmark.

        ⛔ DO NOT ADD AN ngram-mod STAGE AHEAD OF mtp. It reads like free extra
        speculation and it is a 17% LOSS (106.1 -> 88.6). Stages run in order
        and MTP is the fallback, so a weak n-gram match DISPLACES a better MTP
        draft instead of adding to it.

        ⛔ AND DO NOT BENCHMARK AN ngram STAGE BY REPEATING ONE PROMPT. It
        learns across requests, so a second run of the same prompt decodes text
        it has already seen. That artifact measured 404 tok/s here — four times
        the real rate — and briefly made the losing config look like the winner.
        Every number in this file uses each prompt at most once.

        ⛔ n_max IS NOT A "HIGHER IS BETTER" KNOB, AND ITS OPTIMUM MOVES WITH
        CONTEXT LENGTH. This is why the default here is not upstream's. Decode
        tok/s with prefill excluded (streamed, median of 4, unique synthetic
        context per request):

          occupied context     300     6000    25000
          n_max=16 (upstream) 123.2    129.4    99.5
          n_max=8             136.8    146.1    89.3
                             +11.1%   +12.9%  -10.2%

        A deeper draft amortises one expensive verification pass over more
        tokens; a shallower one wastes less work when drafts are rejected. As
        the attention history grows, verification gets costlier and the deeper
        draft wins — which argued, at 65536, for raising this toward upstream's
        16 if long prompts became the norm.

        ⛔ THAT ADVICE IS NOW A CRASH. maxModelLen is 202752, and at that
        context the draft depth is bounded by VRAM rather than by throughput:
        each step reserves ~150 MiB of recurrent-state checkpoints, so raising
        8 to upstream's 16 adds roughly 1.2 GB against ~730 MiB of headroom.
        The server would still START — it is a near-full request that dies, with
        CUDA OOM and exit 139. Measured on the neighbouring ceiling: at 210944,
        n_max=9 and n_max=10 both fail. 8 is the maximum that fits, not a
        preference, and it measured 96.8 tok/s at 180224 against 99.4 at the old
        65536/q8_0/n_max=8 baseline — so the context cost almost nothing.

        Lowering it is safe; raising it requires re-running the near-full
        occupancy test at the configured context before trusting it.

        ⚠️ The short-prompt sweeps are noisier than they look: run-to-run spread
        at a fixed setting reached ±15%, so treat any single-digit difference
        here as a tie. The two effects that reproduced across independent runs
        are MTP itself and the long-context inversion.

        ⛔ n_max HERE IS A CEILING, NOT JUST A DEFAULT. ik accepts a per-request
        override — a `speculative` object in the JSON body alongside `messages`
        — but only DOWNWARD. Verified against the running server 2026-09-13:

          {"speculative":{"stages":[{"type":"mtp","n_max":2}]}}   -> accepted
          {"speculative":{"stages":[{"type":"mtp","n_max":16}]}}  -> 400,
            "n_max=16 exceeds the recurrent speculative startup limit of 8"

        So a client can ask for a shallower draft than this option, never a
        deeper one, and the stage TYPES must match what the server started with.
        Setting 8 here permanently forecloses the depth that wins above ~12k
        context. That is the real cost of this default, and it is the reason to
        revisit it if the workload ever changes — not the ~10% throughput.

        Note that almost nothing sends that field: it is an ik extension, not
        OpenAI, so Home Assistant and every stock client get exactly what is
        configured here. Tune for the traffic that cannot ask.

        Lower n_max also RESERVES LESS VRAM, ~150 MiB per step, and that part is
        exact rather than noisy: 20,458 MiB at 8 against 21,654 at 16. The
        server banner reports the depth it actually chose as
        `llama_spec_ckpt_init: ... per-step (max_tokens=N)`, where N is n_max+1
        — read it there rather than trusting this comment after a version bump.

        p_min is the confidence cutoff, default 0.8. It is NOT the lever the
        VRAM curve made it look like: forcing p_min=0.0 reproduces the same
        inversion, so the depth is what matters. Pinning p_min=0.0 at upstream's
        depth of 16 is the worst of both and collapses to 74.8 tok/s.
      '';
    };

    mtpRequantizeOutputTensor = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = ''
        `-mtprot`: requantize the MTP head's output tensor at load time.

        ⛔ null SINCE THE 3.8 SWAP, AND SETTING IT AGAIN WOULD COST 645 MiB FOR
        NOTHING. ubergarm's Qwen3.8 cut ships the MTP head already at iq4_ks —
        the card says so in as many words ("extra `iq4_ks` mtp head so no need
        for `-mtprot iq4_ks`") — so the flag would re-do work already baked into
        the file.

        On the 3.6 file it was worth 8% on code and 10% on prose (98.0 -> 106.1,
        82.6 -> 90.0), measured 2026-09-13, because that cut did NOT carry the
        requantized head. Kept as an option for exactly that case: a future GGUF
        without one.

        ⚠️ Whether it is needed is a PROPERTY OF THE FILE, not of the engine, so
        re-read the new model card on every swap. The server prints what it did:
          Creating extra output tensor of type iq4_ks for MTP usage.
          Additional memory required is 645.09 MiB
        Absence of that line with this option set to null is the expected state
        now; presence of it means the flag is doing work the file already did.

        Only meaningful when `specStages` contains an mtp stage; it is the MTP
        head's tensor, not the model's.
      '';
    };

    chatTemplateKwargs = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = ''{"enable_thinking": false}'';
      example = "null";
      description = ''
        JSON passed to `--chat-template-kwargs`, setting the SERVER-SIDE default
        for template variables. null omits the flag.

        ⛔ THIS EXISTS BECAUSE HOME ASSISTANT CANNOT SEND IT. Qwen3.6 is a
        reasoning model: left to itself it emits ~2000 characters of reasoning
        before answering, which is right for agentic coding and ruinous for a
        voice command. The fix is one request field, `chat_template_kwargs`,
        and HA's first-party llama_cpp integration exposes no way to send an
        arbitrary body field — its options are Instructions, Control Home
        Assistant, Model, Max tokens, Temperature and Top P, and nothing else.

        So the default belongs on the server, where the client that cannot ask
        gets the right behaviour for free. Measured 2026-09-13 on this host,
        identical prompt:

          no field sent (what HA gets)        1.4s   0 reasoning chars
          client sends enable_thinking=true   5.2s   2094 reasoning chars
          client sends enable_thinking=false  1.4s   0 reasoning chars

        ⛔ AND THE OVERRIDE DIRECTION IS THE WHOLE POINT — verify it still
        holds after an engine bump. A server default that could not be
        overridden would make reasoning unavailable to everything, which is the
        wrong trade for a host whose other job is agentic coding. Because it CAN
        be overridden, the asymmetry is free: HA gets fast answers it never has
        to configure, and any client that wants reasoning asks for it with

          "chat_template_kwargs": {"enable_thinking": true}

        Do not "fix" slow voice by disabling reasoning in the client instead.
        There is no client to configure — that is the entire problem.
      '';
    };

    ctxCheckpoints = lib.mkOption {
      type = lib.types.nullOr lib.types.int;
      default = null;
      description = ''
        `--ctx-checkpoints`: how many recurrent-state snapshots to retain.

        null keeps the upstream default. 0 disables them, which measured +3% on
        code decode (107.8 -> 111.2) at no VRAM cost.

        ⛔ THAT 3% COSTS 18x ON EVERY FOLLOW-UP TURN, AND NO DECODE BENCHMARK
        WILL SHOW IT. Measured 2026-09-13, time to first token across a
        three-turn conversation on a shared 8k prefix:

                            turn 1   turn 2   turn 3
          default            8.45s    0.25s    0.28s
          --ctx-checkpoints 0 5.95s    5.00s    5.05s

        These snapshots are what lets a hybrid model resume from a matching
        prompt prefix. This is a 48-layer GatedDeltaNet model whose recurrent
        state cannot be rebuilt from a KV cache alone, so with them off there is
        nothing to resume from and each turn re-prefills the entire history —
        and the penalty grows with the conversation, because the history does.

        A single-shot prompt pays nothing, which is exactly why the decode sweep
        rated this a win. This host serves a chat assistant. Leave it null.
      '';
    };

    stateDir = lib.mkOption {
      type = lib.types.str;
      default = "/srv/inference";
      description = ''
        Model weights live here, on the encrypted NVMe rather than the root
        filesystem: a quantized 27B is ~15 GB and swapping models accumulates
        several. /srv had 2.5 TB free when this was written.
      '';
    };

    extraArgs = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      example = [
        "--max-cudagraph-capture-size"
        "256"
      ];
      description = ''
        Escape hatch so a flag change does not need a module change.
        Known knob: vLLM's recipe says to reduce --max-cudagraph-capture-size
        (default 512) if CUDA graph capture fails, which is plausible on a card
        this full.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    systemd.tmpfiles.rules = [
      "d ${cfg.stateDir} 0750 root root -"
      # Survives reboots on purpose: a model chosen from the menu should still be
      # the model served after nardol suspends, wakes, or reboots. /run would
      # reset the choice to the default at every wake, which on a host that
      # suspends whenever it is idle means "almost always".
      "d ${profileStateDir} 0755 root root -"
    ];

    environment.systemPackages = lib.mkIf (cfg.engine == "ik-llama") [ nardolModel ];

    virtualisation.oci-containers.containers = lib.mkMerge [
      (lib.mkIf (cfg.engine == "vllm") {
        vllm = {
          image = cfg.image;
          autoStart = true;
          extraOptions = [
            "--gpus=all"
            "--ipc=host" # vLLM needs a large shared-memory segment for NCCL/worker IPC
          ];
          ports = [ "${toString cfg.port}:8000" ];
          volumes = [ "${cfg.stateDir}:/root/.cache/huggingface:rw" ];
          cmd = [
            "--model"
            cfg.model
            "--served-model-name"
            "default"
            "--gpu-memory-utilization"
            (toString cfg.gpuMemoryUtilization)
            "--kv-cache-dtype"
            cfg.kvCacheDtype
            "--reasoning-parser"
            "qwen3"
          ]
          ++ lib.optionals (cfg.quantization != null) [
            "--quantization"
            cfg.quantization
          ]
          ++ lib.optionals (cfg.maxModelLen != null) [
            "--max-model-len"
            (toString cfg.maxModelLen)
          ]
          ++ lib.optionals (cfg.maxCudagraphCaptureSize != null) [
            "--max-cudagraph-capture-size"
            (toString cfg.maxCudagraphCaptureSize)
          ]
          ++ lib.optionals (cfg.toolCallParser != null) [
            "--enable-auto-tool-choice"
            "--tool-call-parser"
            cfg.toolCallParser
          ]
          ++ lib.optional cfg.enforceEager "--enforce-eager"
          ++ lib.optional cfg.enablePrefixCaching "--enable-prefix-caching"
          ++ cfg.extraArgs;

        };
      })

      # ⛔ THE UNIT NAME STAYS docker-ikllama NO MATTER WHICH MODEL IS SERVED.
      # gaming-arbitration.nix conflicts with it by name, nardol-inference-restore
      # starts it by name, and nardol-inference-inhibit binds to it. A container
      # per model would have multiplied all three and quietly broken the handover
      # for every model but the first — so the model is chosen at exec time by
      # ./inference.nix's generated entrypoint, and systemd sees one unit forever.
      (lib.mkIf (cfg.engine == "ik-llama") {
        ikllama = {
          image = cfg.ikLlamaImage;
          autoStart = true;
          extraOptions = [
            "--gpus=all"
            "--entrypoint"
            "/nardol/start"
          ];
          ports = [ "${toString cfg.port}:8080" ];
          volumes = [
            "${ggufRoot}:/models:ro"
            "${ikStartScript}:/nardol/start:ro"
            # Read-only: the container picks a profile, it never chooses one.
            # Writing is `nardol-model`'s job, on the host, where it can validate
            # the name against the flake's own list.
            "${profileStateDir}:${profileStateDir}:ro"
          ];
          # Arguments come from the profile, inside the entrypoint. Passing any
          # here would append them AFTER the generated list, where a duplicate
          # -c or -m silently wins over the profile's.
          cmd = [ ];
        };
      })

      (lib.mkIf (cfg.engine == "llama-cpp") {
        llamacpp = {
          image = cfg.llamaCppImage;
          autoStart = true;
          extraOptions = [ "--gpus=all" ];
          ports = [ "${toString cfg.port}:8080" ];
          volumes = [ "/srv/inference/gguf:/models:ro" ];
          cmd = [
            "-m"
            "/models/${baseNameOf cfg.ggufFile}"
            "--host"
            "0.0.0.0"
            "--port"
            "8080"
            # All layers on the GPU. Anything less silently offloads to CPU and
            # the result is a benchmark of the wrong thing.
            "-ngl"
            "99"
            "-c"
            (toString cfg.maxModelLen)
            # ⛔ --jinja is REQUIRED for tool calling. Without it llama-server
            # falls back to a generic template, the model never emits its
            # <tool_call><function=...> format, and tools silently never fire.
            "--jinja"
            "-fa"
            "on"
            # ⛔ ONE SLOT, explicitly. ik_llama #1932 reports recurrent-state
            # cross-conversation corruption with three or more slots on hybrid
            # models. This is a single-user host; inheriting a multi-user
            # default buys nothing and risks exactly that.
            "--parallel"
            "1"
          ]
          ++ lib.optionals (cfg.kvCacheDtype != null) [
            "-ctk"
            cfg.llamaKvType
            "-ctv"
            cfg.llamaKvType
          ]
          ++ cfg.extraArgs;
        };
      })
    ];

    # ⛔ RATE-LIMIT THE RESTARTS. A misconfigured vLLM restarted 189 times on
    # 2026-09-13 before anyone looked, each attempt pulling ~15 GB of weights
    # into VRAM and dying on CUDA OOM. Unbounded retry turns a config mistake
    # into hours of GPU thrash and buries the original error under identical
    # repeats. Five failures inside ten minutes is enough to conclude it is not
    # coming up on its own.
    # ⛔ THIS MUST NAME THE ENGINE ACTUALLY RUNNING, AND FOR MONTHS IT DID NOT.
    # The old expression collapsed every non-vLLM engine to "llamacpp", so with
    # engine = "ik-llama" the restart limiting was applied to
    # docker-llamacpp.service — and because setting serviceConfig on a name
    # CREATES a unit, that phantom service existed and absorbed the policy while
    # the real docker-ikllama.service ran with systemd's defaults. Verified on
    # the host 2026-09-13: StartLimitIntervalUSec=10s, not the 600s below.
    systemd.services."docker-${
      {
        vllm = "vllm";
        llama-cpp = "llamacpp";
        ik-llama = "ikllama";
      }
      .${cfg.engine}
    }" = {
      # ⛔ StartLimit* ARE [Unit] DIRECTIVES AND systemd IGNORES THEM IN
      # [Service]. They lived in serviceConfig here, which rendered them into
      # the wrong section, so the rate limit was inert for every engine this
      # option has ever had — the unit ran with the 10s/5 default instead of
      # 600s/5. Found 2026-09-13 by reading the generated unit rather than the
      # Nix: `systemctl show` reported StartLimitIntervalUSec=10s while this
      # file said 600. NixOS exposes them as top-level unit options; use those
      # and they land in [Unit].
      startLimitBurst = 5;
      startLimitIntervalSec = 600;
      serviceConfig.RestartSec = lib.mkForce "30s";
    };

    networking.firewall.interfaces.eth0.allowedTCPPorts = [ cfg.port ];
  };
}
