{ lib, pkgs }:
let
  pinCollectorReleaseContract = import ../minas-tirith/pin-collector-release-contract.nix {
    inherit lib;
  };
  pinCollectorRelease = pinCollectorReleaseContract.assertValid (
    import ../minas-tirith/pin-collector-release.nix
  );

  # Keep the manifest permanently owned after its first activation. k3s does not
  # prune a removed auto-deploy file, so `staged = false` must render an inert
  # object set rather than dropping the file and leaving the previous release live.
  pinCollectorInertImage = "registry.invalid/pin-collector/inert@sha256:${lib.concatStrings (lib.replicate 64 "0")}";
  pinCollectorApiImage =
    if pinCollectorRelease.staged then pinCollectorRelease.apiImage else pinCollectorInertImage;
  pinCollectorModelImage =
    if pinCollectorRelease.staged then pinCollectorRelease.modelImage else pinCollectorInertImage;
  pinCollectorApiDigest =
    if pinCollectorRelease.staged then
      lib.removePrefix "ghcr.io/edgarsaldivar/pin-collector-api@sha256:" pinCollectorApiImage
    else
      lib.concatStrings (lib.replicate 64 "0");
  pinCollectorGitRevision =
    if pinCollectorRelease.staged then
      pinCollectorRelease.gitRevision
    else
      lib.concatStrings (lib.replicate 40 "0");
  pinCollectorManifest = pkgs.replaceVars ../minas-tirith/manifests/pin-collector.yaml.in {
    apiImage = pinCollectorApiImage;
    modelImage = pinCollectorModelImage;
    gitRevision = pinCollectorGitRevision;
    statefulReplicas = if pinCollectorRelease.staged then "1" else "0";
    apiReplicas = if pinCollectorRelease.enabled then "1" else "0";
    modelReplicas = if pinCollectorRelease.enabled then "1" else "0";
    migrationSuspended = if pinCollectorRelease.enabled then "false" else "true";
    migrationJobName = "pin-collector-migrate-${builtins.substring 0 12 pinCollectorApiDigest}";
  };

  # coredns-custom — resolve minas' public hostnames to its LAN address.
  #
  # D13: a Pod resolving e.g. tautulli.saldivar.io gets the PUBLIC address, so its
  # request leaves the network and must return through NAT loopback. This maps those
  # names to 10.0.1.6 for cluster DNS, exactly as networking.hosts does for the host.
  #
  # The list is imported from minas-tirith/traefik-hostnames.nix — the SAME file
  # networking.hosts uses — so the two cannot drift.
  #
  # Delivered as a `.server` file, not `.override`, deliberately. k3s' Corefile carries
  # `import /etc/coredns/custom/*.override` INSIDE the .:53 block and
  # `import /etc/coredns/custom/*.server` at top level. The main block already uses the
  # `hosts` plugin for NodeHosts, and a second `hosts` in the same block is a config
  # error — so this defines its own server block for the zone instead.
  #
  # `fallthrough` matters: names NOT in the list (notably ha-pelargir.saldivar.io,
  # which lives on pelargir) fall through to `forward` and resolve normally.
  #
  # coredns-custom is the ONE CoreDNS customisation that is k3s-supported and
  # upgrade-safe. Both replicas mount it (packaged and coredns-ha), optional: true.
  minasHostnames = import ../minas-tirith/traefik-hostnames.nix;
  corednsCustom = pkgs.writeText "coredns-custom.yaml" ''
    # GENERATED by pelargir/manifests.nix from minas-tirith/traefik-hostnames.nix.
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: coredns-custom
      namespace: kube-system
    data:
      saldivar.server: |
        saldivar.io:53 {
            errors
            cache 30
            hosts {
    ${lib.concatMapStringsSep "\n" (h: "            10.0.1.6 ${h}") minasHostnames}
                fallthrough
            }
            forward . /etc/resolv.conf
        }
  '';

  minasTraefik = (import ./minas-traefik-manifest.nix { inherit lib pkgs; }).minasTraefik;
in
{
  inherit
    corednsCustom
    minasTraefik
    pinCollectorManifest
    pinCollectorRelease
    ;
}
