# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, nixos-hardware, ... }:

let
  # Get the path to the current Nix file
  currentFile = toString ./.;
  # Construct the relative path to the firmware files
  firmwarePath = "${currentFile}/../../firmware/pi4";
  # Copy firmware files from local configuration to the Nix store
  firmwareFiles = pkgs.runCommand "local-firmware" {} ''
    cat ${currentFile}
    ls -l ${currentFile}
    ls -l ../${currentFile}
    mkdir -p $out
    echo "Copying firmware files from ${firmwarePath}"
    ls -l ${firmwarePath}
    cp -r ${firmwarePath}/* $out/
  '';
in
{
  sound.enable = true;
  nixpkgs.hostPlatform.system = "aarch64-linux";
  nixpkgs.config.allowUnsupportedSystem = true;
  console.enable = false;
  boot.initrd.availableKernelModules = [ 
    "xhci_pci" 
    "usbhid" 
    "uas" 
    "bcm2835_rng" 
    "bcm2835_wdt"
    "usb_storage"
    "vc4"
    "pcie_brcmstb" # required for the pcie bus to work
    "reset-raspberrypi" # required for vl805 firmware to load
   # "gasket" # Kernel module for Coral USB Accelerator
   # "apex"   # Kernel module for Coral USB Accelerator
  ];
  boot.initrd.kernelModules = [ "vc4" "bcm2835_dma" "i2c_bcm2835" ];
  boot.kernelModules = [ "vc4" "snd_bcm2835" ];
  boot.extraModulePackages = [ ];
  swapDevices = [ ];
  hardware.enableRedistributableFirmware = true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";


  # GPU
  hardware = {
    raspberry-pi = {
      "4" = {
        apply-overlays-dtmerge.enable = true;
        fkms-3d.enable = true;
      };
    };
    deviceTree = {
      enable = true;
      filter = lib.mkForce "*rpi-4-*.dtb";
    };
  };

  # eeprom
  environment.systemPackages = with pkgs; [
    libraspberrypi
    raspberrypi-eeprom
  ];

  # Audio
  hardware.pulseaudio.enable = true;

  #Bluetooth
  systemd.services.btattach = {
    before = [ "bluetooth.service" ];
    after = [ "dev-ttyAMA0.device" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      ExecStart = "${pkgs.bluez}/bin/btattach -B /dev/ttyAMA0 -P bcm -S 3000000";
    };
  };
 # Automate update PI firmware
  environment.shellAliases = {
      raspi-cpu = ''
        sudo vcgencmd get_throttled && sudo vcgencmd measure_temp
      '';
      raspi-firmware-update = ''
        sudo mkdir -p /mnt && \
        sudo mount /dev/disk/by-label/FIRMWARE /mnt && \
        BOOTFS=/mnt FIRMWARE_RELEASE_STATUS=stable sudo -E rpi-eeprom-update -d -a && \
        sudo umount /mnt
      '';
    };
  
  # Ensure the firmware files are included in the final image
  fileSystems."/firmware" = {
    device = "/dev/disk/by-label/FIRMWARE";
    fsType = "vfat";
    options = [ "rw" ];
  };

  environment.etc."firmware-setup".source = pkgs.runCommand "raspberry-pi-firmware" {} ''
    mkdir -p $out/firmware
    cp -r ${firmwareFiles}/* $out/firmware/
  '';
  
}