# P1E — GPU access for k3s Pods on minas-tirith.
#
# THE PROBLEM THIS SOLVES
# -----------------------
# `hardware.nvidia-container-toolkit` on NixOS is **CDI-only**. It emits a CDI spec at
# /var/run/cdi/nvidia-container-toolkit.json and puts no nvidia runtime on PATH — which
# is exactly what docker's plex and jellyfin use (`DeviceRequests{driver: cdi}`), and it
# demonstrably works.
#
# k3s never sees any of it. k3s auto-detects an nvidia runtime by looking for
# `nvidia-container-runtime` on PATH, finds nothing, and writes a containerd config with
# zero nvidia references. So Pods have no GPU access at all.
#
# WHY NOT JUST TURN CDI ON IN CONTAINERD
# --------------------------------------
# It already is. containerd >= 2.0 (this host runs 2.2.5-k3s2) enables CDI by default
# with /var/run/cdi already in its spec dirs, so there is nothing to enable.
#
# A pod annotated `cdi.k8s.io/gpu: nvidia.com/gpu=0` still gets nothing, and that is NOT
# evidence CDI is broken: **kubelet never forwards user pod-metadata annotations into the
# CRI ContainerConfig**, which is the only place containerd's CDI injection looks. That
# path cannot work by design, whatever containerd is configured to do.
#
# WHAT THIS DOES INSTEAD
# ----------------------
# Registers the toolkit's CDI-mode runtime shim as a containerd runtime named `nvidia`,
# surfaced to Kubernetes as RuntimeClass `nvidia`. The shim reads the SAME host CDI spec
# docker already proves correct, so Pods get a byte-identical device and library set.
#
# Deliberately NOT the device-plugin's own in-container CDI generation (`cdi-cri`
# strategy): that regenerates a spec from inside a container assuming an FHS layout, and
# this host's driver libraries live at /nix/store paths. Reusing the host spec avoids
# that entire class of NixOS breakage.
#
# BLAST RADIUS ON DOCKER: none by construction. Docker never reads k3s's containerd
# config and never execs this shim. The CDI spec, driver and device nodes are untouched.
# Rollback is removing this module and restarting k3s.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  # The `tools` output carries the runtime shims; the default output only has nvidia-ctk.
  # Referenced through the option so a toolkit version bump cannot silently desync this
  # from the CDI spec generator that produced the spec it reads.
  toolkit = config.hardware.nvidia-container-toolkit.package.tools;

  # The `.cdi` variant is pinned to CDI mode. Using it directly is why no extra
  # config.toml for the shim is needed — the plain `nvidia-container-runtime` would
  # pick a mode at runtime and could fall back to the legacy hook path, which needs
  # nvidia-container-cli (absent on this host).
  nvidiaRuntime = "${toolkit}/bin/nvidia-container-runtime.cdi";

  # k3s regenerates config.toml on every start and stamps it "DO NOT EDIT", but the
  # generated file carries `imports = [".../config-v3.toml.d/*.toml"]`. Dropping a file
  # there is the upgrade-safe extension point.
  #
  # Only ADDITIVE tables are declared: the base config defines
  # `...containerd.runtimes.runc`, and this adds a sibling `.nvidia`. Appending to
  # `services.k3s.containerdConfigTemplate` instead would redeclare
  # `[plugins.'io.containerd.cri.v1.runtime']`, which the base already defines — a TOML
  # duplicate-key error, not a merge.
  dropIn = pkgs.writeText "nvidia-cdi.toml" ''
    # GENERATED by hosts/nixos/minas-tirith/k3s-gpu.nix — DO NOT EDIT HERE.
    [plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.nvidia]
      runtime_type = "io.containerd.runc.v2"

    [plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.nvidia.options]
      BinaryName = "${nvidiaRuntime}"
      # Must match runc's setting in the base config. A cgroup-driver mismatch between
      # runtimes produces pods that start and then fail on resource accounting.
      SystemdCgroup = true
  '';

  dropInDir = "/var/lib/rancher/k3s/agent/etc/containerd/config-v3.toml.d";
in
{
  # Label the node so the device plugin DaemonSet can select it rather than tolerating
  # every node. --node-label only applies at REGISTRATION, and this node is already
  # registered, so the label is also applied imperatively once (see K3S-PHASE1-PLAN.md).
  # Declared here so a rebuilt/rejoined node gets it automatically.
  services.k3s.extraFlags = [ "--node-label=saldivar.io/gpu=nvidia" ];

  systemd.tmpfiles.rules = [ "d ${dropInDir} 0755 root root -" ];

  # Runs before k3s starts so a fresh boot has the runtime registered on the first
  # containerd start rather than needing a second restart.
  systemd.services.k3s-nvidia-runtime = {
    description = "Register the NVIDIA CDI runtime with k3s containerd";
    wantedBy = [ "multi-user.target" ];
    before = [ "k3s.service" ];
    path = with pkgs; [ coreutils ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      install -d -m 0755 ${dropInDir}
      install -m 0644 ${dropIn} ${dropInDir}/nvidia-cdi.toml
      echo "registered nvidia runtime -> ${nvidiaRuntime}"
    '';
  };
}
